Repository lacework/terraform-provisioning, pull requests merged in 2020-06, with the labels that each got.

#25 Add env vars to GCP README
  gcp/README.md
Labels: documentation

#28 docs(gcp): fix TF_VAR prefix in README.md
  gcp/README.md
  gcp/variables.tf
Labels: documentation

#31 feat: AWS terraform modules
  aws/main.tf
  aws/modules/cloudtrail/examples/complete-cloudtrail/main.tf
  aws/modules/cloudtrail/examples/existing-cloudtrail-iam-role/main.tf
  aws/modules/cloudtrail/examples/existing-cloudtrail/main.tf
  aws/modules/cloudtrail/main.tf
  aws/modules/cloudtrail/variables.tf
  aws/modules/config/examples/custom-config/main.tf
  aws/modules/config/examples/default-config/main.tf
  aws/modules/config/main.tf
  aws/modules/config/output.tf
  aws/modules/config/variables.tf
  aws/modules/iam_role/examples/custom-config/main.tf
  aws/modules/iam_role/examples/default-config/main.tf
  aws/modules/iam_role/main.tf
  aws/modules/iam_role/output.tf
  aws/modules/iam_role/variables.tf
  aws/variables.tf
Labels: enhancement

#36 doc(azure): adds README.md
  azure/README.md
Labels: documentation

#40 fix(gcp): pass resource_level to LW integrations
  gcp/main.tf
Labels: bug

#45 feat(aws): consolidated cloudtrail + multitenancy
  aws/README.md
  aws/modules/cloudtrail/examples/complete-cloudtrail/main.tf
  aws/modules/cloudtrail/examples/consolidated-cloudtrail-multiple-lacework-tenants/main.tf
  aws/modules/cloudtrail/examples/consolidated-cloudtrail-multiple-lacework-tenants/sub_account.tf
  aws/modules/cloudtrail/examples/consolidated-cloudtrail/main.tf
  aws/modules/cloudtrail/examples/existing-cloudtrail-iam-role/main.tf
  aws/modules/cloudtrail/examples/existing-cloudtrail/main.tf
  aws/modules/cloudtrail/main.tf
  aws/modules/cloudtrail/output.tf
  aws/modules/cloudtrail/variables.tf
  aws/modules/config/output.tf
Labels: enhancement
