Repository lacework/terraform-provisioning, pull requests merged in 2020-07, with the labels that each got.

#50 refactor(GCP): convert templates into TF Modules
  aws/README.md
  aws/main.tf
  aws/modules/iam_role/examples/default-config/main.tf
  gcp/README.md
  gcp/main.tf
  gcp/modules/audit_log/examples/environment-variables-project-level-audit-log/main.tf
  gcp/modules/audit_log/examples/existing-service-account-org-level-audit-log/main.tf
  gcp/modules/audit_log/examples/organization-level-audit-log/main.tf
  gcp/modules/audit_log/examples/project-level-audit-log/main.tf
  gcp/modules/audit_log/main.tf
  gcp/modules/audit_log/output.tf
  gcp/modules/audit_log/variables.tf
  gcp/modules/config/examples/environment-variables-project-level-config/main.tf
  gcp/modules/config/examples/existing-service-account-org-level-config/main.tf
  gcp/modules/config/examples/organization-level-config/main.tf
  gcp/modules/config/examples/project-level-config/main.tf
  gcp/modules/config/main.tf
  gcp/modules/config/output.tf
  gcp/modules/config/variables.tf
  gcp/modules/service_account/examples/custom-config-organization-level-account/main.tf
  gcp/modules/service_account/examples/default-config-project-level-account/main.tf
  gcp/modules/service_account/main.tf
  gcp/modules/service_account/output.tf
  gcp/modules/service_account/variables.tf
  gcp/organization_level.tf
  gcp/project_level.tf
  gcp/variables.tf
Labels: documentation, enhancement

#52 fix(gcp): activate required apis correctly
  gcp/modules/audit_log/variables.tf
  gcp/modules/service_account/variables.tf
Labels: bug

#55 feat(aws): added CloudTrail bucket server-side encryption
  aws/README.md
  aws/modules/cloudtrail/main.tf
  aws/modules/cloudtrail/variables.tf
Labels: enhancement
